server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: postgres
    password: beyzanur
  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        globally_quoted_identifiers: true
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

